CREATE TABLE IF NOT EXISTS users
(
	id UUID
		CONSTRAINT pk_users PRIMARY KEY,
	created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    modified_time TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
	email TEXT NOT NULL,
	full_name TEXT NOT NULL,
	password TEXT NOT NULL,
	lock JSONB,
	metadata JSONB,
	UNIQUE(email)
);
